name: Manual CI for Assignment Testing

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23.6.0" # Use the Node.js version your project needs

      - name: Install Dependencies
        run: npm install

      - name: Compile the Code
        run: npx hardhat compile

      - name: Run Tests
        id: run-tests # Save the output for use in the next step
        run: |
          npx hardhat test | tee test-output.txt

      - name: Verify 35 Passing Tests
        run: |
          if grep -q "35 passing" test-output.txt; then
            echo "All tests passed (35 passing)."
          else
            echo "Test count does not match 35 passing. Failing the job."
            exit 1
          fi
